# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13.5

    working_directory: /go/src/github.com/HewlettPackard/hpecli
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get -v -t -d ./...

      - run: |
          go test .\... -v -coverprofile=cp.out
          go tool cover -html=cp.out -o coverage.html
          mv coverage.html $TEST_RESULTS
      - run: ./build.sh
      - store_test_results:
          path: $TEST_RESULTS
