# Golang CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/HewlettPackard/hpecli
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: go get -v -t -d ./...
      - run: mkdir -p /tmp/test-results/
      - run: |
          go test ./... -coverprofile=cp.out
          go tool cover -html=cp.out -o coverage.html
          mv coverage.html /tmp/test-results/      
      - sonarcloud/scan
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/HewlettPackard/hpecli
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: ./build.sh

workflows:
  version: 2
  test-build-publish:
    jobs:
      - test:
          context: SonarCloud
      - build:
          filters:
            branches:
              only: release
